### PR TITLE
Allow modifying OrganizationMember after initial creation

### LINKED ISSUE #12: User roles are reset to AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE after logout
## Steps to reproduce

1. Configure Sentry 23.7.1 with this plugin
2. Set `AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE = 'member'` in `sentry.conf.py`
3. Login with user A
4. Use a local admin account to assign user A the role `owner`
5. Logout with user A
6. Re-login with user A

## Actual result

The role of user A is reset to `member`.

## Expected result

The role of user A is kept as whatever has been assigned after initial creation.

Please let me know if you need any further information. Thanks for your continued maintenance of this integration.

### PR DESCRIPTION
**Pull request by spawnia**
Resolves https://github.com/PMExtra/sentry-auth-ldap/issues/12

Currently untested, I can do the same as in https://github.com/PMExtra/sentry-auth-ldap/pull/8#issuecomment-1609189361 when I have a maintenance window.

### CODE REVIEW

**Comment by PMExtra** [comment]
@spawnia 
I'm sorry for my previous mistake.
After digging further. I think #12 is not a bug, you are requesting a new feature.

For now, the roles were mapped from LDAP groups completely.
You should change your LDAP group assignments to assign the user to the Sentry role.

This pull request will break the updating behavior.

I think we have two ways to resolve it:

1. Do not update the existing OrganizationMember only if `_get_effective_sentry_role()` is None;
2. Make a new option to indicate update the existing OrganizationMember or not.

**Comment by spawnia** [comment]
> You should change your LDAP group assignments to assign the user to the Sentry role.

We don't use that option, but perhaps that would be the way to go.

My expectation for `AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE` was that it specifies the default when users are added, and does not prevent manual changes thereafter. I can see how one might want to have the group to role mapping override manual changes.

If we keep the current behaviour that always overrides, we might want to document that.

Alternatively, I agree that we should not make a judgement call as to which settings are always overridden and which are preserved and offer fine-grained configuration instead. Perhaps a set of configuration options that include the term `DEFAULT` could be introduced next to the existing ones, e.g. `AUTH_LDAP_SENTRY_DEFAULT_ORGANIZATION_ROLE_TYPE`?

**Comment by PMExtra** [comment]
Currently, we have two sources to get the role:

1. Call `_get_effective_sentry_role()` to get the role mapping from LDAP groups.
2. Get from the `AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE` option. (Only works when the first source got None)

The first source should be synced with Sentry when every login. However, I think the second source is not necessary for syncing.

In summary. I think `AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE` already works as a default value. That's what I said previously:

> Do not update the existing `OrganizationMember` only if `_get_effective_sentry_role()` is None.

Certainly, we can rename the option (add `DEFAULT_`) but I think it's not necessary.

Adding a new `AUTH_LDAP_SENTRY_DEFAULT_ORGANIZATION_ROLE_TYPE` option next to the existing ones is not a good idea, they are too similar!

If we really want to keep the original behavior, maybe we can add a Boolean option to indicate whether to override the existing OrganizationMember.

**Comment by spawnia** [comment]
Got it. I rewrote the code to always sync the role if it is specified through groups, but only initialize it once if not.

**Comment by spawnia** [comment]
Feel free to modify this pull request as you see fit, I am not familiar with Python nor with Django.

**Comment by PMExtra** [comment]
LGTM, can you test it at your convenience?

**Comment by spawnia** [comment]
Thanks for the modifications. I have a maintenance window on Friday and plan to test it then.

**Comment by spawnia** [comment]
Thanks for the patience @PMExtra, I just got around to testing this change. Login and logout still work nicely, and the user role is preserved.

**Pull request merged**
