### PR TITLE
Update OrganizationMember update_or_create field due to Sentry updates

### PR DESCRIPTION
**Pull request by bryanjuho**
Sentry has changed their [OrganizationModel's user field to user_id](https://github.com/getsentry/sentry/blob/affc86677fef90bc5e1895ffd07337c41cb0b72c/src/sentry/models/organizationmember.py#L192).  Commit: [Link](https://github.com/getsentry/sentry/commit/cd5d40f7cefe7061ba50eec854888b77751f5e36)

This causes FieldError because user used to be an User object.

### CODE REVIEW

**Comment by PMExtra** [comment]
Is it a broken change that won't work with the older Sentry?

**Comment by bryanjuho** [comment]
No, this is a very recent change(v23.6.0). This package will need to apply the changes in this PR for versions >= 23.6.0 only.

**Comment by PMExtra** [comment]
@bryanjuho As you said, I think it's a broken change because it can no longer work with the older Sentry.

In other words, we should bump a major version to 23.6.0 to indicate this plugin needs Sentry 23.6.0 and later. I thought it was not a good versioning policy but we are already on this way.

In totally,
Sentry < 21.9.0 should work with `sentry-ldap-auth==2.9.0`
Sentry >= 21.9.0 and Sentry < 23.6.0 should work with `sentry-auth-ldap==21.9.11`
Sentry >= 23.6.0 should work with `sentry-auth-ldap==23.6.0` (which includes this PR)

Do you agree to the above?

**Comment by bryanjuho** [comment]
> @bryanjuho As you said, I think it's a broken change because it can no longer work with the older Sentry.
> 
> In other words, we should bump a major version to 23.6.0 to indicate this plugin needs Sentry 23.6.0 and later. I thought it was not a good versioning policy but we are already on this way.
> 
> In totally, Sentry < 21.9.0 should work with `sentry-ldap-auth==2.9.0` Sentry >= 21.9.0 and Sentry < 23.6.0 should work with `sentry-auth-ldap==21.9.11` Sentry >= 23.6.0 should work with `sentry-auth-ldap==23.6.0` (which includes this PR)
> 
> Do you agree to the above?

Oh I get it. 
Yes, Your summary is accurate.

**Comment by Saintel** [comment]
Dear @PMExtra, could your please release the new version with this fix? 
We can't use the Sentry after update without it.
Thank you!

**Comment by spawnia** [comment]
@bryanjuho thank you for this update. I installed your branch with the following addition to `sentry/enhance-image.sh` and found that it works fine:

```sh
# TODO revert to sentry-auth-ldap proper with https://github.com/PMExtra/sentry-auth-ldap/pull/8
apt-get update
apt-get install --yes git
rm --recursive /var/lib/apt/lists/*
pip install -e git+https://github.com/bryanjuho/sentry-auth-ldap.git@master#egg=sentry-auth-ldap
```

**Comment by bryanjuho** [comment]
> @bryanjuho thank you for this update. I installed your branch with the following addition to `sentry/enhance-image.sh` and found that it works fine:
> 
> ```shell
> # TODO revert to sentry-auth-ldap proper with https://github.com/PMExtra/sentry-auth-ldap/pull/8
> apt-get install --yes git
> pip install -e git+https://github.com/bryanjuho/sentry-auth-ldap.git@master#egg=sentry-auth-ldap
> ```

Good to be of help.
Obviously as soon as this PR gets merged and pypi package is updated, I recommend you to revert `enhance_image.sh` to this repository because my fork was only for tests. Thanks!

**Comment by spawnia** [comment]
> Obviously as soon as this PR gets merged and pypi package is updated, I recommend you to revert enhance_image.sh to this repository because my fork was only for tests. Thanks!

Hence the TODO I also added 😉

**Comment by PMExtra** [comment]
sentry-auth-ldap=23.6.0 was released.

**Pull request merged**
